[env]
TERM = "screen-256color"

[font]
size = 11

[font.bold]
style = "Bold"

[font.normal]
style = "Regular"

# [[keyboard.bindings]]
# chars = "\u001BOH"
# key = "Left"
# mode = "AppCursor"
# mods = "Command"
#
# [[keyboard.bindings]]
# chars = "\u001BOF"
# key = "Right"
# mode = "AppCursor"
# mods = "Command"
#
# [[keyboard.bindings]]
# chars = "\u0015"
# key = "Back"
# mods = "Command"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "NumpadAdd"
mods = "Command"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Command"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "NumpadSubtract"
mods = "Command"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Command"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Command"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Command"

[[keyboard.bindings]]
action = "Hide"
key = "H"
mods = "Command"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Command"

[[keyboard.bindings]]
action = "Quit"
key = "W"
mods = "Command"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Command"

[[keyboard.bindings]]
action = "None"
key = "F"
mods = "Command|Control"

[[keyboard.bindings]]
action = "None"
key = "F"
mode = "~Search"
mods = "Command"

[window]
opacity = 1
decorations = "none"
dynamic_padding = true

[window.padding]
x = 0
y = 0

[general]
import = ["themes/blink.toml"]

